### PR TITLE
Added two example, non-notebook deployments

### PR DESCRIPTION
**Pull request by nathangeology**
## Description
** There is some reformatting of files according to the webstorm linter. **
The primary purpose of this pull request is to add two MVP example deployments. One to bokeh/panel and one is a simple HTML webpage deployment.

## Related Issue
https://github.com/JustinGOSSES/wellioviz/issues/99#issue-632464906
Enable wellioviz to work with Dash or Panel or other python viz things

## Motivation and Context
This allows users to see the basics of how to use this javascript package as a part of panel, bokeh, and (thanks to panel) plotly as well. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] example python web app integrations

## Checklist:

- [x] My code follows the code style of this project. (I think! Can discuss if formatting needs adjusting)
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (Might need some help to integrate this with the docs in a sane way)
- [ ] I have added tests to cover my changes. (Not sure what this entails for this type of change)
- [ ] All new and existing tests passed. (see above)

### CODE REVIEW

**Comment by nathangeology** [comment]
@JustinGOSSES I'm going to start working on some refactoring of the wellioviz library next as part of the hackathon. Afterwards, I'll see about adding in some more sophisticated integrations and examples.

**Comment by dcslagel** [comment]
Hi @nathangeology,

I tried to run the the example_panel_app by installing panel with ```pip install panel``` and running 
```bash
cd wellioviz/example_deployments/example_panel_app
python main.py
```
and it died on this error:

```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    with open('panel_idx.html', 'r', encoding='utf-8') as html_file:
FileNotFoundError: [Errno 2] No such file or directory: 'panel_idx.html'
```

Is there additional setup steps or does panel_idx.html need to be added?

Thanks!,
DC

**Comment by nathangeology** [comment]
try running `panel serve example_panel_app --show ` from example_deployments directory. Also, I'm updating the html with a few changes since I moved it from the original 'myapp' folder on my machine to this examples folder for the main project. <- DONE

**Comment by JustinGOSSES** [comment]
This is great work @nathangeology  . 

I got it working pretty easily. A few thoughts:

- Maybe we should move it inside of docs folder, so it doesn't get pushed to NPM . Maybe make a panel_example folder in there? Not certain what is best or whether moving its location will break things?
- Looks like you're hard coding the LAS file currently. Are you eventually envisioning being able to load & manipulate LAS files in python via GUI in html/css/js? I'm not familar with panel, so not 100% sure what the vision is yet.
- Need to add notes to docs so there are some basic instructions for this and notes about where it is going.

**Comment by JustinGOSSES** [comment]
Do people think we should merge this pull request and keep working on it or work on pull request? My bias is to move its location then merge, but open to anything.

**Comment by dcslagel** [comment]
Hi @nathangeology , @JustinGOSSES ,

Great, got the panel running with Nathan's ```panel serve example_panel_app --show``` information.

How about creating a t20-wellioviz branch or next release branch and merging to there?  This could work well because it would give a separate branch to do any tidying up, directory changes and other considerations as preparation for a later merge to the master.

**Comment by nathangeology** [comment]
Ok, the last thing is to update the documentation and then this panel example deployment should be completed. Going to work on refactoring and making better panel example apps using wellioviz.

**Review by JustinGOSSES — APPROVED** [review]

**Pull request merged**
