### PR TITLE
changes by ehsan

### PR DESCRIPTION
**Pull request by mehsan1**
## Description
1. Rectangle needed to have top/bottom depth not height
2. Rectangles had to be plotted on random x-axis in case of multiple on same depth
3. Title added hover line showing depth/curve values
4. Simple Header introduced to have simple start/end values on scale
5. click event added, to send/return depth of click on plot area to angualr/node/react component
6. there are many others as well

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
Can we changed variable to not be named random as it isn't random but a fixed percentage? That could be very confusing for future developers.

**Comment by JustinGOSSES** [comment]
Really like the idea of that click event. Have you tested that in all those frameworks?

**Comment by mehsan1** [comment]
1. yes we can change the name, you can do that and it will not effect anything as it is in library.
2. yes, I tested this click event in angular and it will work in all js frameworks.

**Comment by JustinGOSSES** [comment]
I see you use 

"header_complex" `let header_complex = template_overall["header_complex"]` as a new variable. 
and
"is_depth_track" in ` let is_depth_track = template_overall["is_depth_track"]` as a new variable
and 
well_id in `let well_id = template_overall["well_id"]`

They then need to be included in:
- putIncomingSparseJsonIntoPlottingTemplate() function
- getFakeIncomingSparseDataExample() function 
- curveBoxTemplateExamples() function 

None of these functions are edited to include the new variables.

**Comment by JustinGOSSES** [comment]
Taking out lines:
923 & 925 in index.js
     `     .style('overflow-y',"auto")
          ` & 
 `.style('max-height',height_components+"px")`

Would disable scroll.. is that intential?
          .style('max-height',height_components+"px")`

**Comment by mehsan1** [comment]
yes
remove 923 & 925 in index.js
scroll will be handled by front end application

because multiple tracks will need to have one scroll.

**Comment by mehsan1** [comment]
> I see you use
> 
> "header_complex" `let header_complex = template_overall["header_complex"]` as a new variable.
> and
> "is_depth_track" in ` let is_depth_track = template_overall["is_depth_track"]` as a new variable
> and
> well_id in `let well_id = template_overall["well_id"]`
> 
> They then need to be included in:
> 
> * putIncomingSparseJsonIntoPlottingTemplate() function
> * getFakeIncomingSparseDataExample() function
> * curveBoxTemplateExamples() function
> 
> None of these functions are edited to include the new variables.

Ok I will do this and push changes

**Comment by JustinGOSSES** [comment]
Also, can we have the default behavior be the depth track is shown? 

Right now the depth track doesn't show at all if the depth_track variable is missing.  That will confuse new developers. Better behavior is to have it shown by default and only take off if there is a variable that tells it to have that behavior.

**Comment by JustinGOSSES** [comment]
Too many complete and partial changes in here....so will close and attempt to reuse some of the improvements later individually

**Pull request closed without merging**
